# AUTO-GENERATED from schema/capabilities — DO NOT EDIT
# python tools/generate_capabilities.py

"""Generated facade protocols and SetMode."""
from __future__ import annotations

from enum import Enum
from typing import Protocol, Any, Optional, Iterator

from machine_config.capabilities.result import Result
from machine_config.capabilities.errors import CapabilityError


class SetMode(str, Enum):
    MERGE = 'Merge'
    REPLACE = 'Replace'


class MetaHandle(Protocol):
    def get_model(self) -> dict[str, Any]: ...
    def set_model(self, model: dict[str, Any], mode: SetMode = SetMode.MERGE) -> Result[None, CapabilityError]: ...


class MachineHandle(Protocol):
    def get_model(self) -> dict[str, Any]: ...
    def set_model(self, model: dict[str, Any], mode: SetMode = SetMode.MERGE) -> Result[None, CapabilityError]: ...


class ClearBoxHandle(Protocol):
    def get_model(self) -> dict[str, Any]: ...
    def set_model(self, model: dict[str, Any], mode: SetMode = SetMode.MERGE) -> Result[None, CapabilityError]: ...


class OptionalComponentsHandle(Protocol):
    def clearbox(self) -> Result[ClearBoxHandle, CapabilityError]: ...


class TrainHandle(Protocol):
    def get_model(self) -> dict[str, Any]: ...
    def set_model(self, model: dict[str, Any], mode: SetMode = SetMode.MERGE) -> Result[None, CapabilityError]: ...
    def get_scanner(self) -> dict[str, Any]: ...
    def set_scanner(self, model: dict[str, Any], mode: SetMode = SetMode.MERGE) -> Result[None, CapabilityError]: ...
    def get_light_source(self) -> dict[str, Any]: ...
    def set_light_source(self, model: dict[str, Any], mode: SetMode = SetMode.MERGE) -> Result[None, CapabilityError]: ...
    def get_collimator(self) -> dict[str, Any]: ...
    def set_collimator(self, model: dict[str, Any], mode: SetMode = SetMode.MERGE) -> Result[None, CapabilityError]: ...
    def get_scanner_card(self) -> dict[str, Any]: ...
    def set_scanner_card(self, model: dict[str, Any], mode: SetMode = SetMode.MERGE) -> Result[None, CapabilityError]: ...
    def optional_components(self) -> OptionalComponentsHandle | None: ...


class TrainCollection(Protocol):
    def __len__(self) -> int: ...
    def get(self, index: int) -> Result[TrainHandle, CapabilityError]: ...
    def __iter__(self) -> Iterator[TrainHandle]: ...


class OpcuaHandle(Protocol):
    def get_model(self) -> dict[str, Any]: ...
    def set_model(self, model: dict[str, Any], mode: SetMode = SetMode.MERGE) -> Result[None, CapabilityError]: ...


class MachineConfigFile(Protocol):
    def file_version(self) -> str: ...
    def meta(self) -> MetaHandle: ...
    def machine(self) -> MachineHandle: ...
    def optical_trains(self) -> TrainCollection: ...
    def optical_train(self, index: int) -> Result[TrainHandle, CapabilityError]: ...
    def opcua(self) -> Result[OpcuaHandle, CapabilityError]: ...
    def save(self, path: str | None = None) -> Result[None, CapabilityError]: ...
    def close(self) -> None: ...
